# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
 webSrc: 'covid19-web'
 webSrcBuild: ${webSrc}/build

pool:
  vmImage: 'ubuntu-latest'

  steps:    
    - task: PublishArtifacts
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'covid19'
        publishLocation: 'pipeline'
  
  jobs:
  - deployment: VMDeploy
    displayName: Deploy
    pool:
      vmImage: 'Ubuntu-18.04'
    dependsOn: 'PublishArtifacts'  
    environment:
      name: covid19-node-vm-001
      resourceType: VirtualMachine
      tags: covid19-node-vm-001
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: 'pm2 stop Covid19-Web'        
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/s'
              Contents: '**'
              TargetFolder: '/home/hpcclabs/covid19/covid19'
              OverWrite: true
          - task: CmdLine@2
            inputs:
              script: 'pm2 start Covid19-Web'



