# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

#do not trigger ci on pull requests
pr: none

pool: 
  vmImage: ubuntu-latest
  

jobs:
  - job: Publish
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'covid19'
        publishLocation: 'pipeline'

  - deployment: VMDeploy
    displayName: Deploy
    pool:
      vmImage: 'Ubuntu-18.04'
    dependsOn: 'Publish'  
    environment:
      name: covid19-node-vm-001
      resourceType: VirtualMachine
      tags: covid19-node-vm-001
    strategy:
      runOnce:
        deploy:
          steps:
          - task: CmdLine@2
            inputs:
              script: 'pm2 stop Covid19-Web'        
          - task: CopyFiles@2
            inputs:
              SourceFolder: '/home/hpcclabs/azagent/_work/1/covid19/s/covid19-web'
              Contents: '**'
              TargetFolder: '/home/hpcclabs/covid19/covid19/covid19-web'
              OverWrite: true
          - task: CmdLine@2
            inputs:
              script: 'npm install'
              workingDirectory: '/home/hpcclabs/covid19/covid19/covid19-web'
          - task: CmdLine@2
            inputs:
              script: 'pm2 start Covid19-Web'
          - task: DeleteFiles@1
            inputs:
              SourceFolder: '/home/hpcclabs/azagent/_work/1/covid19/s/covid19-web'
              Contents: '*'
              


