EXPORT CatalogUSStates := MODULE
  
  EXPORT STRING2 ToStateCode(STRING50 name) := FUNCTION
    code := CASE(name, 
                 'ALABAMA' => 'AL',
                 'ALASKA' => 'AK',
                 'ARIZONA' => 'AZ',
                 'ARKANSAS' => 'AR',
                 'AMERICAN SAMOA' => 'AS',
                 'CALIFORNIA' => 'CA',
                 'COLORADO' => 'CO',
                 'CONNECTICUT' => 'CT',
                 'DELAWARE' => 'DE',
                 'DISTRICT OF COLUMBIA' => 'DC',
                 'FLORIDA' => 'FL',
                 'GEORGIA' => 'GA',
                 'GUAM' => 'GU',
                 'HAWAII' => 'HI',
                 'IDAHO' => 'ID',
                 'ILLINOIS' => 'IL',
                 'INDIANA' => 'IN',
                 'IOWA' => 'IA',
                 'KANSAS' => 'KS',
                 'KENTUCKY' => 'KY',
                 'LOUISIANA' => 'LA',
                 'MAINE' => 'ME',
                 'MARYLAND' => 'MD',
                 'MASSACHUSETTS'=> 'MA',
                 'MICHIGAN' => 'MI',
                 'MINNESOTA' => 'MN',
                 'MISSISSIPPI' => 'MS',
                 'MISSOURI' => 'MO',
                 'MONTANA' => 'MT',
                 'NEBRASKA' => 'NE',
                 'NEVADA' => 'NV',
                 'NEW HAMPSHIRE' => 'NH',
                 'NEW JERSEY' => 'NJ',
                 'NEW MEXICO' => 'NM',
                 'NEW YORK' => 'NY',
                 'NORTH CAROLINA' => 'NC',
                 'NORTH DAKOTA' => 'ND',
                 'NORTHERN MARINA ISLANDS' => 'MP',
                 'OHIO' => 'OH',
                 'OKLAHOMA' => 'OK',
                 'OREGON' => 'OR',
                 'PENNSYLVANIA' => 'PA',
                 'PUERTO RICO' => 'PR',
                 'RHODE ISLAND' => 'RI',
                 'SOUTH CAROLINA' => 'SC',
                 'SOUTH DAKOTA' => 'SD',
                 'TENNESSEE' => 'TN',
                 'TEXAS' => 'TX',
                 'UTAH' => 'UT',
                 'US VIRGIN ISLANDS' => 'VI',
                 'VERMONT' => 'VT',
                 'VIRGINIA' => 'VA',
                 'WASHINGTON' => 'WA',
                 'WEST VIRGINIA' => 'WV',
                 'WISCONSIN' => 'WI',
                 'WYOMING' => 'WY',
                 '');
    return code;
  END;  
  

  EXPORT states := DATASET([
    {'ALABAMA','AL'},
    {'ALASKA','AK'},
    {'AMERICAN SAMOA','AS'},
    {'ARIZONA','AZ'},
    {'ARKANSAS','AR'},
    {'CALIFORNIA','CA'},
    {'COLORADO','CO'},
    {'CONNECTICUT','CT'},
    {'DELAWARE','DE'},
    {'DISTRICT OF COLUMBIA','DC'},
    {'FLORIDA','FL'},
    {'GEORGIA','GA'},
    {'GUAM','GU',},
    {'HAWAII','HI'},
    {'IDAHO','ID'},
    {'ILLINOIS','IL'},
    {'INDIANA','IN'},
    {'IOWA','IA'},
    {'KANSAS','KS'},
    {'KENTUCKY','KY'},
    {'LOUISIANA','LA'},
    {'MAINE','ME'},
    {'MARYLAND','MD'},
    {'MASSACHUSETTS','MA'},
    {'MICHIGAN','MI'},
    {'MINNESOTA','MN'},
    {'MISSISSIPPI','MS'},
    {'MISSOURI','MO'},
    {'MONTANA','MT'},
    {'NEBRASKA','NE'},
    {'NEVADA','NV'},
    {'NEW HAMPSHIRE','NH'},
    {'NEW JERSEY','NJ'},
    {'NEW MEXICO','NM'},
    {'NEW YORK','NY'},
    {'NORTH CAROLINA','NC'},
    {'NORTH DAKOTA','ND'},
    {'NORTHERN MARINA ISLANDS','MP'},
    {'OHIO','OH'},
    {'OKLAHOMA','OK'},
    {'OREGON','OR'},
    {'PENNSYLVANIA','PA'},
    {'PUERTO RICO','PR'},
    {'RHODE ISLAND','RI'},
    {'SOUTH CAROLINA','SC'},
    {'SOUTH DAKOTA','SD'},
    {'TENNESSEE','TN'},
    {'TEXAS','TX'},
    {'UTAH','UT'},
    {'US VIRGIN ISLANDS','VI'},
    {'VERMONT','VT'},
    {'VIRGINIA','VA'},
    {'WASHINGTON','WA'},
    {'WEST VIRGINIA','WV'},
    {'WISCONSIN','WI'},
    {'WYOMING','WY'}
  ], {STRING50 name, STRING2 code});


  EXPORT stateCodeDict := DICTIONARY(states, {code => name});
  EXPORT stateNameDict := DICTIONARY(states, {name => code});
 
  EXPORT toState(STRING2 stateCode) := stateCodeDict[stateCode].name;
  EXPORT toCode(STRING stateName) := stateNameDict[stateName].code;


END;

