EXPORT UKPopulation := MODULE

  EXPORT filePath := '~hpccsystems::covid19::file::public::UKpopulation::v1::population.flat';  
                       

  EXPORT layout := RECORD
    STRING Code;
    STRING Name;
    STRING Geography1;
    UNSIGNED All_ages;
    UNSIGNED age_0;
    UNSIGNED age_1;
    UNSIGNED age_2;
    UNSIGNED age_3;
    UNSIGNED age_4;
    UNSIGNED age_5;
    UNSIGNED age_6;
    UNSIGNED age_7;
    UNSIGNED age_8;
    UNSIGNED age_9;
    UNSIGNED age_10;
    UNSIGNED age_11;
    UNSIGNED age_12;
    UNSIGNED age_13;
    UNSIGNED age_14;
    UNSIGNED age_15;
    UNSIGNED age_16;
    UNSIGNED age_17;
    UNSIGNED age_18;
    UNSIGNED age_19;
    UNSIGNED age_20;
    UNSIGNED age_21;
    UNSIGNED age_22;
    UNSIGNED age_23;
    UNSIGNED age_24;
    UNSIGNED age_25;
    UNSIGNED age_26;
    UNSIGNED age_27;
    UNSIGNED age_28;
    UNSIGNED age_29;
    UNSIGNED age_30;
    UNSIGNED age_31;
    UNSIGNED age_32;
    UNSIGNED age_33;
    UNSIGNED age_34;
    UNSIGNED age_35;
    UNSIGNED age_36;
    UNSIGNED age_37;
    UNSIGNED age_38;
    UNSIGNED age_39;
    UNSIGNED age_40;
    UNSIGNED age_41;
    UNSIGNED age_42;
    UNSIGNED age_43;
    UNSIGNED age_44;
    UNSIGNED age_45;
    UNSIGNED age_46;
    UNSIGNED age_47;
    UNSIGNED age_48;
    UNSIGNED age_49;
    UNSIGNED age_50;
    UNSIGNED age_51;
    UNSIGNED age_52;
    UNSIGNED age_53;
    UNSIGNED age_54;
    UNSIGNED age_55;
    UNSIGNED age_56;
    UNSIGNED age_57;
    UNSIGNED age_58;
    UNSIGNED age_59;
    UNSIGNED age_60;
    UNSIGNED age_61;
    UNSIGNED age_62;
    UNSIGNED age_63;
    UNSIGNED age_64;
    UNSIGNED age_65;
    UNSIGNED age_66;
    UNSIGNED age_67;
    UNSIGNED age_68;
    UNSIGNED age_69;
    UNSIGNED age_70;
    UNSIGNED age_71;
    UNSIGNED age_72;
    UNSIGNED age_73;
    UNSIGNED age_74;
    UNSIGNED age_75;
    UNSIGNED age_76;
    UNSIGNED age_77;
    UNSIGNED age_78;
    UNSIGNED age_79;
    UNSIGNED age_80;
    UNSIGNED age_81;
    UNSIGNED age_82;
    UNSIGNED age_83;
    UNSIGNED age_84;
    UNSIGNED age_85;
    UNSIGNED age_86;
    UNSIGNED age_87;
    UNSIGNED age_88;
    UNSIGNED age_89;
    UNSIGNED age_above_90;
  END;

  EXPORT ds := DATASET(filePath, layout, FLAT);  

END;